services:
  - name: web
    type: web
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: REDIS_URL
        value: redis://redis:6379
    autoDeploy: true

  - name: celery
    type: worker
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: REDIS_URL
        value: redis://redis:6379
      - key: RUN_CELERY
        value: "true"
    autoDeploy: true

  - name: redis
    type: redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere 
